### ISSUE TITLE
Willy Byte crashes if Mockingboard 4c is enabled

### ISSUE THREAD

**Issue by JDW1** [a2-4am/4cade#666]
I am using a IIc with Mockingboard 4c (by Ian Kim) installed.  I am booting Total Replay 5.2 from a FloppyEMU.

When I play the game normally, it works fine, but there is no Mockingboard audio. 

When I manually enable the MB4c via the following commands, the Mockingboard music then will play on the opening screen:

]CALL-151
*C403:FF FF
*C600G (to restart)

But if I press space while the music is playing on the opening screen, the game will crash (freeze).  Even if I don't press SPACE, when I let the opening screen finish, it will crash.

In other words, there seems to be a conflict with Willy Byte in Total Replay after enabling the MB4c.  But if I don't enable MB4c, all is well (just no Mockingboard audio).

**Comment by peterferrie** [comment]
That's interesting because we do the $C403:FF FF ourselves in TR, so if
it's not happening then something else is going wrong.
If you run TR v5.0, start Berzap, press ctrl-C to enter the sound config,
and select Mockingboard Sound/Speech, then play a game, does it hang, too?

**Comment by JDW1** [comment]
It seems you want me to use TR version 5.0, not 5.2 or 5.2.  Can you please provide a download link to that version, because I am not finding it on the TR Internet Archive page:

https://archive.org/details/TotalReplay

And amusingly, the Internet Archive refuses to allow me to go back in time to grab earlier versions from that page!

**Comment by JDW1** [comment]
OK.  After much searching, I found TR 5.0 on one of my hard drives, thankfully.  Even so, it would be best if there was an easy-to-download repository of old versions for times like this.

I booted TR 5.0 from my FEMU, selected BERZAP, then pressed RETURN to load the game.  When it came up, I pressed CTRL-C.  It presented me with many choices:

NOISE PRODUCTION
• The dreaded "Apple Speaker"
• Mockingboard Sound 2
• Mockingboard Sound/Speech (which you told me to choose)
• Mockingboard "A" (which is what the MB4c actually is — no speech)
• Mockingboard "C"

I get out of the settings screen and go back to the main screen and press RETURN, and yes, **it freezes with the black screen**, quite similar to Willy Byte.

I rebooted and this time tried "Mockingboard A" and that works fine.  Music plays from the right speaker, and firing (sound effects) come from the left speaker.  And no, I did not need to manually enable the MB4c either.

**Comment by peterferrie** [comment]
Okay, thank you for testing!  I agree that it could be easier to fetch older versions.
Now, to the results, Willy Byte is asking the MB4c if it supports speech, and the MB4c is saying yes, but then it fails when asked to actually talk.
Berzap demonstrates the same when you override our default configuration.  I will fix Willy Byte to use our configuration instead, and not ask the MB4c.  We detect speech (or lack of) differently, in a way that works with the MB4c.

**Comment by peterferrie** [comment]
fixed in a857cdf453be0931e4018d904bde10d43ffe1276

**Comment by wyatt-wong** [comment]
James, 

I frequently build the latest the latest binary of most (if not all) of 4am GitHub source into binaries which include but not limited to 4cade, 4sports, wizard-reply, adventure-replay, etc.
I published the latest build of the following in the past few days of 2025 in two of my facebook groups:

Total Replay build 4057Instant Replay build 305
Adventure Replay build 177

I found another source update in 4cade so I am going to publish a newer build of Total Replay today.

Best Regards,
Wyatt Wong 

    On Monday, January 6, 2025 at 02:13:42 AM GMT+8, Peter Ferrie ***@***.***> wrote:  
 
 


fixed in a857cdf

**Comment by JDW1** [comment]
Wyatt, I just tested your build.  I can hear the Mockingboard audio when I test it in a virtual IIe in the Virtual ][ emulator, but when I booted my real IIc from it (with MB4c installed), all Mockingboard audio is OFF, even in SkyFox.  And even if I manually ENABLE MB4c, it still doesn't work.  And if I reboot from the release version of Total Reply 5.2, then I see Mockingboard is enabled when booting, and SkyFox Mockingboard audio plays.  So something is wrong with that new build because it disables all MB4c audio playback, playing audio through the stock speaker only.

**Comment by JDW1** [comment]
Do I need to create a new bug report, or will Peter reopen this one?

**Comment by wyatt-wong** [comment]
> Do I need to create a new bug report, or will Peter reopen this one?

I think you need to raise another issue and link to this one mentioning that the issue is still not fixed.

**Comment by peterferrie** [comment]
Does the SkyFox audio work in build 4052 and not in build 4053?  If so, then that's an entirely separate issue which would need to be tracked newly.

**Comment by JDW1** [comment]
Sorry for my extreme delay in replying, but I've been quite busy with other tasks.

I downloaded [build 4152 here](https://github.com/appleiifanclub/a2-4am_4cade_bin/releases), and booted my IIc.  TR loads, but it has the same problem as earlier builds in that it does NOT say "Mockingboard in slot 4" in the opening text screen, and even SkyFox audio does not work.  

When I reboot from the public release version of TR 5.2, it shows "Mockingboard in slot 4" and I can confirm SkyFox audio plays normally.

This confirms what I said about build 4057 in a previous post.  Builds 4057 and 4152 have the same problem.  Neither shows "Mockingboard in slot 4" in the opening screen, and I can confirm there is NO Mockingboard audio playing on compatible games like SkyFox.  Furthermore, if I try to manually enable the Mockingboard with the following commands when using build 4057 or 4152, the commands do not work and there is no "Mockingboard in slot 4" text shown when starting TR:

]CALL-151
*C403:FF FF
*C600G (to restart)

What all this means is that something has broken Mockingboard 4c audio (for the Apple IIc) in builds newer than the public release version of TR 5.2.

**Comment by wyatt-wong** [comment]
You may check my latest build in my GitHub repository.Sent from my iPhone 12 Pro MaxOn 7 Jan 2025, at 10:13 PM, James Wages ***@***.***> wrote:﻿
Wyatt, I just tested your build.  I can hear the Mockingboard audio when I test it in a virtual IIe in the Virtual ][ emulator, but when I booted my real IIc from it (with MB4c installed), all Mockingboard audio is OFF, even in SkyFox.  And even if I manually ENABLE MB4c, it still doesn't work.  And if I reboot from the release version of Total Reply 5.2, then I see Mockingboard is enabled when booting, and SkyFox Mockingboard audio plays.  So something is wrong with that new build because it disables all MB4c audio playback, playing audio through the stock speaker only.

**Comment by peterferrie** [comment]
I need to know specifically the behaviour of builds 4052 and 4053.  Does SkyFox audio work in build 4052 and not in build 4053? 
The latest build hasn't fixed anything because I don't know yet where to look.

**Comment by wyatt-wong** [comment]
I don’t have Total Replay build 4052 and 4053 anymore. I have just recently started to keep different  builds of Total Replay but it is impossible for me to keep every single build.If you need to find the delta changes between build 4052 and build 4053, you are most probably need to review the change log in GitHub page but I guessed it would be difficult to check it out.Sent from my iPhone 12 Pro MaxOn 2 Feb 2025, at 1:43 AM, Peter Ferrie ***@***.***> wrote:﻿
I need to know specifically the behaviour of builds 4052 and 4053.  Does SkyFox audio work in build 4052 and not in build 4053?
The latest build hasn't fixed anything because I don't know yet where to look.

**Comment by JDW1** [comment]
> I need to know specifically the behaviour of builds 4052 and 4053. 

Peter, if you or someone else could please give me exact URLs to 4052 and 4053, I can then put them on my SD card (FloppyEMU) and test.  (I don't even know the build number of the public release version of TR 5.2 because when I start it, there is no info other than saying it is 5.2.)

**Comment by peterferrie** [comment]
Wyatt, please "git checkout <hash of commit 4052>" (visible in the commit
history) and build from the fetched code. Then you will have build 4052.
Same idea for 4053.

**Comment by wyatt-wong** [comment]
> Wyatt, please "git checkout <hash of commit 4052>" (visible in the commit
> history) and build from the fetched code. Then you will have build 4052.
> Same idea for 4053.
> […](#)

There doesn't seem to have a "commit number" entry and so the problem is how do I know which specific commit corresponds to the commit 4052 and 4053.

**Comment by wyatt-wong** [comment]
@peterferrie Please find the Total Replay build 4052 and 4053 attached:

[Total Replay build 4052.zip](https://github.com/user-attachments/files/18632644/Total.Replay.build.4052.zip)

![Image](https://github.com/user-attachments/assets/9c40a148-495e-4594-8c7a-4dcfcd8170d0)

[Total Replay build 4053.zip](https://github.com/user-attachments/files/18632646/Total.Replay.build.4053.zip)

![Image](https://github.com/user-attachments/assets/f3132802-151a-404b-8f4b-f6ba35890b39)

**Comment by peterferrie** [comment]
Thank you, and can you tell me if the audio behaviour in Skyfox differs
between those two builds?  If it does then I can fix it right away.

**Comment by JDW1** [comment]
Unfortunately, I didn't have access to those two builds when I began my weekend, and today is Monday here in Japan, so I am at work now.  It will need to wait until after work.  That means it will be at least 10 hours from now.  Very sorry for the delay.  I do wish to thank Wyatt for making them.  I'd be lost without Wyatt's kind assistance!

**Comment by peterferrie** [comment]
No worries about the delay, and yes, thank you very Wyatt for making those
available.

**Comment by JDW1** [comment]
Peter,
To get you the faster answer, I spent my lunch break testing:

**Short answer**: 4052 enables the Mockingboard 4c (MB4c), but 4053 does not.  The public release v.5.2 also enables MB4c.  Willy Byte music plays in 4052 & 5.2, but it freezes, as mentioned earlier in this thread.

**Full Answer**: My video showing all the testing should answer any questions you might have:

https://youtu.be/-RpwLwmd3gs

**Comment by wyatt-wong** [comment]
> Unfortunately, I didn't have access to those two builds when I began my weekend, and today is Monday here in Japan, so I am at work now. It will need to wait until after work. That means it will be at least 10 hours from now. Very sorry for the delay. I do wish to thank Wyatt for making them. I'd be lost without Wyatt's kind assistance!

You are most welcome. I am sorry I didn't provide the build before the end of 02-Feb-2025 so you can test it. But it is nice that you managed to squeeze some time to test the build 4052 and build 4053.

**Comment by peterferrie** [comment]
Thank you both, I now have a lead on the cause!

**Comment by peterferrie** [comment]
Might be fixed in latest.

**Comment by JDW1** [comment]
> Might be fixed in latest.
> […](#)

When Wyatt is able to post that build, Peter, then I will test it as soon as I can after that.

**Comment by appleiifanclub** [comment]
@peterferrie Please check the pull request in https://github.com/a2-4am/wizard-replay

**Comment by appleiifanclub** [comment]
> > Might be fixed in latest.
> > […](#)
> 
> When Wyatt is able to post that build, Peter, then I will test it as soon as I can after that.

I will post the new version to my GitHub page.

**Comment by JDW1** [comment]
Bad news.  I downloaded build 4161 here:
https://github.com/appleiifanclub/a2-4am_4cade_bin/releases/

I see Mockingboard in slot 4 when I boot, and I can also confirm SkyFox audio plays just fine.  And I can even confirm the Mockingboard 4c music plays fine in Willy Byte during the initial splash screen.  But if you leave it alone and wait until the music stops playing, the screen fills with text and some of the characters flash, and it stays there forever.  If I reboot and try again, this time pressing the space bar to end the initial splash screen, the machine seems to reboot because the drive LED comes on and I hear the head banging, just as if I had pressed CTRL-OpenApple-ESC, however nothing appears on screen and it just freezes.

What that means is this:
1. Mockingboard 4c music is working, even in Willy Byte
2. WillyByte crashes when you try to get past the initial splash screen.

So basically nothing has really changed since I opened this Willy Byte bug report on Jan. 4th.  

I am, of course, happy to test future builds until this problem is fixed.

Thanks, Peter for all your time and effort on this!

**Comment by wyatt-wong** [comment]
> Bad news.  I downloaded build 4161 here:
> https://github.com/appleiifanclub/a2-4am_4cade_bin/releases/
> 
> I see Mockingboard in slot 4 when I boot, and I can also confirm SkyFox audio plays just fine.  And I can even confirm the Mockingboard 4c music plays fine in Willy Byte during the initial splash screen.  But if you leave it alone and wait until the music stops playing, the screen fills with text and some of the characters flash, and it stays there forever.  If I reboot and try again, this time pressing the space bar to end the initial splash screen, the machine seems to reboot because the drive LED comes on and I hear the head banging, just as if I had pressed CTRL-OpenApple-ESC, however nothing appears on screen and it just freezes.
> 
> What that means is this:
> 1. Mockingboard 4c music is working, even in Willy Byte
> 2. WillyByte crashes when you try to get past the initial splash screen.
> 
> So basically nothing has really changed since I opened this Willy Byte bug report on Jan. 4th.  
> 
> I am, of course, happy to test future builds until this problem is fixed.
> 
> Thanks, Peter for all your time and effort on this!

You mean consider to use mobile phone to take a few screen shots or a simply record a video to show the results.

**Comment by JDW1** [comment]
> You mean consider to use mobile phone to take a few screen shots or a simply record a video to show the results.

Here is a video showing what I wrote in my previous post:

https://youtu.be/hTeTherXzfg?si=11bYtSM6JCa1crZf

**Comment by wyatt-wong** [comment]
> > You mean consider to use mobile phone to take a few screen shots or a simply record a video to show the results.
> 
> Here is a video showing what I wrote in my previous post:
> 
> https://youtu.be/hTeTherXzfg?si=11bYtSM6JCa1crZf

@peterferrie I think this issue can be considered to re-open as I think it couldn't be fix within a short period of time.

**Comment by peterferrie** [comment]
Agreed.  It's back to being a Willy Byte problem now that the MB4C slot issue is fixed.

**Comment by peterferrie** [comment]
Can you start a level in both Rescue Raiders and Zoo Master?  Both incorporate speech, and if both work then the problem is not the speech anymore.

**Comment by JDW1** [comment]
> Can you start a level in both Rescue Raiders and Zoo Master? Both incorporate speech, and if both work then the problem is not the speech anymore.

Unfortunately, the Mockingboard 4c doesn’t have a speech chip, so it’s not possible to confirm anything speech-related.

**Comment by peterferrie** [comment]
I know that the MB4C doesn't have speech, but Willy Byte's original problem
was that the MB4C was responding as though it had speech, causing Willy
Byte to hang.
I thought that I had fixed that issue, and maybe the current issue is a
hang in a different location, but if either Rescue Raiders or Zoo Master
hang, too, then it's still a speech-related issue.
Just troubleshooting.

**Comment by JDW1** [comment]
Understood, Peter.  I shall test **Rescue Raiders** & **Zoo Master** using TR build **4161** this evening after work and report back then.

**Comment by wyatt-wong** [comment]
> Understood, Peter. I shall test **Rescue Raiders** & **Zoo Master** using TR build **4161** this evening after work and report back then.

Total Replay build 4166 published.

**Comment by JDW1** [comment]
Very sorry for my delayed reply.

Rescue Raiders plays the Demo just fine, and I can press ESC and play the game without issue too.

Zoo Master asked me if I want to have the sound ON and I typed “Y” and then the game proceeded to play fine, with sound through the stock speaker.

I tested build 4161. 

Yes, I am aware that Wyatt added 4166 but I’ve not tested 4166 yet. I will wait for your reply, Peter, before doing further testing.

**Comment by peterferrie** [comment]
Thank you James, no worries about the delay.  I will keep looking.  No need
to try a later version.

**Comment by peterferrie** [comment]
is it fixed in 4283?

**Comment by JDW1** [comment]
> is it fixed in 4283?

I’m traveling internationally right now and will be away from home for another week. I will test when I get back.

**Comment by peterferrie** [comment]
Cool, thank you!

**Comment by JDW1** [comment]
More bad news, Peter.

Wyatt Wong very kindly prepared build 4307 for me today.  I tested that on my Apple IIc (with Mockingboard 4c) using Kay Koba's SPIISDv2 SmartPort drive.  When TR boots, it shows that the MB4c loads.  When I then choose Willy Byte, the game loads and the music plays through the MB4c just fine.  If I leave it alone and don't touch keyboard or joystick, when the music finishes playing, instead of going to another screen, the internal 5.25" drive will access (disk use LED lights), and the machine freezes.

After that freeze, I flipped the power switch off for several seconds, then back on, and then I did the same thing except this time I pressed a button on my joystick soon after the music began playing.  That took me to another screen where I filled out info.  It later took me to the screen where you see the green ALU at left and POWR, RAM, LOOP, MAP, IF, KEYB, DISK, CLOK at bottom.  I was able to run through that just fine.  But then when I returned the little guy to the middle and jumped up, he floated up as expected, but then the internal 5.25" drive accessed (disk use LED lights), and the machine froze at that point.

I then pressed OpenApple-CTRL-RESET.  It showed the MB4c load as expected.  I then loaded WillyByte.  The music played for about 10 seconds and then I hit the SPACEBAR.  That took me to the next screen which asks if I want to use KEYBOARD or JOYSTICK.  I didn't answer that and just waited.  I then returned me to the opening splash screen and the music began again.  This time I waited until all the graphics were painted on screen and then I hit SPACEBAR again.  That ended the music but the screen froze at that point.

I pressed OpenApple-CTRL-RESET again, launched WillyByte, let the music play but I quickly pressed SPACEBAR.  I pressed J for Joystick.  I typed HEY for the message and pressed RETURN.  It then took me to the ALU programming screen. I jumped around and then went to the middle and jumped up.  The little guy vanished.  A couple seconds later the internal 5.25" drive accessed.  The machine froze again.

So clearly, the problem remains.  Quite unfortunate, but that the current status of things.

—James W.

**Comment by peterferrie** [comment]
Thank you, that description helped.  I've made more changes.  Please try
again when you have a moment.

**Comment by JDW1** [comment]
“Try again” with what build number?

**Comment by JDW1** [comment]
Wyatt Wong once again did me a kindness and prepared build 4309 for me to test.  Same exact problem as I reported in my earlier post where I tested 4307.  Here's a short video showing you exactly what I am seeing and hearing...

https://youtu.be/kRTE1DT6zto

—James

**Comment by wyatt-wong** [comment]
Thanks for the numerous tests performed by @JDW1

**Comment by peterferrie** [comment]
now it runs.  e5e989d3f48f244eb7d64093908aa26cb324304a
